language: node_js
node_js:
- node
- 0.10.40
- iojs
script: npm test
branches:
  only:
  - master
before_install:
  - sudo apt-get install imagemagick --fix-missing
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
